kind: Service
apiVersion: v1
metadata:
 name: redis
 namespace: {{ .Values.namespace }}
spec:
 ports:
 - port: 6379
   targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
 name: redis
 namespace: {{ .Values.namespace }}
subsets:
 - addresses:
     - ip: 192.168.33.101
   ports:
     - port: 6379